# Generated by Django 3.2 on 2023-10-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_user_todo_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='username',
            new_name='user',
        ),
    ]
